# Generated by Django 5.1.5 on 2025-01-27 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dados_biometricos',
            name='utilizador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.utilizadores'),
        ),
        migrations.AlterField(
            model_name='recordes',
            name='utilizador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.utilizadores'),
        ),
        migrations.AlterField(
            model_name='recordesnomes',
            name='utilizador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.utilizadores'),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='utilizador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.utilizadores'),
        ),
    ]
